log_level: debug
prometheus:
  configs:
    - name: test
      wal_directory: 'test_wal'
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels: {agent: 'yes'}
      remote_write:
        - url: http://localhost:8080/cortex/api/distributor/api/prom/push
