---
kind: pipeline
name: check

platform:
  os: linux
  arch: amd64

workspace:
  base: /src
  path: agent

steps:
- name: test
  image: grafana/loki-build-image:0.9.0
  commands:
  - make BUILD_IN_CONTAINER=false test
  depends_on:
  - clone

- name: lint
  image: grafana/loki-build-image:0.9.0
  commands:
  - make BUILD_IN_CONTAINER=false lint
  depends_on:
  - clone

...
